# Aula 03 - Entrada de dados com input( O Usuario escreve os dados atraves do comando input)
nome = input("Digite seu nome:")
Idade = input("Digite a sua Idade:")
Altura = input("Digite a sua Altura:")
Cidade = input("Digite a sua Cidade:")
Estado_Civel = input("Digite o Estado civel:")
print("Nome:",nome)
print("Idade:",Idade)
print("Altura:",Altura)
print("Cidade:",Cidade)
print("Estado_Civel:",Estado_Civel)